// generated by comb on 2011-12-28T03:11:08Z
var modules = function() {
  var registry = {}
  return {
    register: function(name, module) {
      registry[name] = module
    },
    require: function(name) {
      return registry[name]()
    }
  }
}()
var require = modules.require
// app.js => app
modules.register('app', function() {
  var exports = {}
  exports.run = function() {
    var textbox = require('widgets/textbox')
    var emailbox = require('widgets/emailbox')
    var uri = require('utils/uri')
    alert(uri.bestUri)
    var bdays = require('utils/date')
    bdays.whatsMyBday()
  }
  return exports
})
// controllers/articles.js => controllers/articles
modules.register('controllers/articles', function() {
  var exports = {}
  // articles...
  return exports
})
// controllers/edit.js => controllers/edit
modules.register('controllers/edit', function() {
  var exports = {}
  // edit controller
  return exports
})
// utils/date.js => utils/date
modules.register('utils/date', function() {
  var exports = {}
  var myBday = '24/11/1982'
  
  var whatsMyBday = function() {
    alert(myBday)
  }
  
  exports.whatsMyBday = whatsMyBday
  return exports
})
// utils/uri.js => utils/uri
modules.register('utils/uri', function() {
  var exports = {}
  exports.bestUri = 'yeahnah.org'
  return exports
})
// widgets/combos/megatable.js => widgets/combos/megatable
modules.register('widgets/combos/megatable', function() {
  var exports = {}
  // lol mega table
  return exports
})
// widgets/emailbox.js => widgets/emailbox
modules.register('widgets/emailbox', function() {
  var exports = {}
  // lol an email box, does nothing
  return exports
})
// widgets/textbox.js => widgets/textbox
modules.register('widgets/textbox', function() {
  var exports = {}
  exports.name = 'textbox'
  exports.make = function() {
    // macking an textbox
  }
  return exports
})
// end of comb output
