require_relative "comb/version"
require 'time'

module Comb
  def self.assemble(path)
    out = []
    library_path = path
    out << "// generated by comb on #{Time.now.utc.iso8601}"
    out << <<-eos
var modules = function() {
  var registry = {}
  return {
    register: function(name, module) {
      registry[name] = module
    },
    require: function(name) {
      return registry[name]()
    }
  }
}()
var require = modules.require
    eos
    Dir.glob(library_path + '/**/*.js').each do |path|
      file = path.gsub(library_path, '').gsub(/^\//, '')
      mod = file.gsub(/\.js$/, '')
      out << <<-eos
// #{file} => #{mod}
modules.register('#{mod}', function() {
#{File.open(path) { |f| f.read }.split("\n").collect { |line| "  #{line}" }.join("\n")}
})
      eos
    end
    out << "// end of comb output"
    out.join("\n")
  end
end
